import 'dart:async';
import 'api.dart';

class AuthenticationService {
  final Api _api;

  AuthenticationService({ required Api api}) : _api = api;

  //final StreamController<Autogenerated> _userController = StreamController<Autogenerated>();

 // Stream<Autogenerated> get user => _userController.stream;
}





